import { Roboto } from 'next/font/google'
import './globals.css'
import Flores from "./components/flowers"


const inter = Roboto({ 
  weight: ['400'],
  subsets: ['latin'] })

export const metadata = {
  title: 'Pedido',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-pink-200`}>{children}
      <Flores />
      </body>
    </html>
  )
}
